### ISSUE TITLE
Memory management in webR

### ISSUE THREAD

**Issue by lionel-** [georgestagg/webR#128]
# Current state

This section shows (approximatively, some tweaks are still needed) the current state of memory management in webR.

## Protecting and unprotecting singular objects

Objects must be protected from the worker thread, not from the main thread. Consider:

```typescript
async function foo() {
  const obj = await webR.evalR('rnorm(1)');
  await obj.keep();
}
```

Because of concurrency, R code may run between the two `await` expressions, causing `obj` to be GC'd before it has a chance to be protected. We don't have any choice but to automatically preserve all objects returned to the main thread. The `keep()` method must be called implicitly by the worker.

On the other hand, because Javascript doesn't have reliable object finalisers, `free()` can't be called implicitly. If the main thread doesn't explictly free these objects, memory is leaked:

```typescript
async function foo() {
  const obj = await webR.evalR('rnorm(1)');

  return await bar(obj);
}

async function bar(obj: RObject) {
  const other = await webR.evalR('runif(1)');
  const out = await webR.evalR('x + y', { x: obj, y: other});

  return await out.toNumber();
}
```

Code on the main thread must protect-unwind object release in `finally` clause:

```typescript
async function foo() {
  // Implicit `keep()`
  const obj = await webR.evalR('rnorm(1)');

  // Need to protect-unwind `free()` as soon as created
  try {
    return await bar(obj);
  } finally {
    obj.free();
  }
}
```

`try / finally` can quickly get out of hands with this singular unprotection approach though:

```typescript
async function bar(obj: RObject) {
  const other = await webR.evalR('runif(1)');

  try {
    const out = await webR.evalR('x + y', { x: obj, y: other});

    try {
      return await out.toNumber();
    } finally {
      out.free();
    }
  } finally {
    other.free();
  }
}
```

To avoid this increasing nestedness we need some way of unprotecting multiple objects at once.

## Evaluating for side effects

Implicit protection gets in the way when evaluating R code for side effects. min the following example the return value is leaked because the user forgot to explictly release it.

```typescript
async function printNorm(): void {
  await webR.evalR('print(rnorm(1))');
}
```

The user needs to remember to release the returned object immediately with a rather heavy boilerplate:

```typescript
async function printNorm(): void {
  await (await webR.evalR('print(rnorm(1))')).free();
}
```

Alternatively we could add arguments to `evalR()`, `captureR()`, `newRObject()`, etc to turn off implicit protection:

```typescript
async function printNorm(): void {
  await webR.evalR('print(rnorm(1))', undefined, false);
}
```

This spares a channel communication (one fewer `await`). But this has the downside that users would need to look up the signature of these methods to figure out which argument they need to pass. In the example above, we need to skip the `env` argument with an explicit `undefined`.

## The case of `captureR()`

The return value of `captureR()` is more complicated to deal with than that of `evalR()`. It currently returns two objects, a `result: RObject` and an `output: (string | RObject)[]`. The second object is an array that contains stdout/stderr outputs converted to JS strings and message/warning conditions wrapped in `RObject`s. There is an indefinite number of objects protected by `captureR()` that need to be released.

Dealing with the outputs using `free()` wouldn't be practical as the caller would have to loop over the array in a `finally` clause. One way to solve this would be for `captureR()` to be paired with a helper that frees everything automatically, but this is one more idiosyncratic thing to keep in mind for users of this API. It would be easy to only manage the memory of `result` and forget about `output`, especially since most of the time the output array only contains JS objects.

# Proposals

## Minimalistic shelters

To simplify the release of objects and avoid nested `try / finally` blocks, we need to create some sort of shelter to which objects can be added and released all at once.

We could implement shelters with a simple JS object:

```typescript
interface Shelter {
  [key: string]: RObject;
}
```

The following purge helper would be exposed as `webR.purge`. It's not an async function because users shouldn't manipulate objects after calling `purge()`. The objects can be freed at any time in the future.

```typescript
function shelterPurge(shelter: Shelter) {
  Object.keys(shelter).forEach((key) => shelter[key].free());
}
```

Here is an example where the callee `bar()` creates a shelter for itself. The caller `foo()` frees its own object with `free()`, as before:

```typescript
async function foo() {
  const obj = await webR.evalR('rnorm(1)');

  try {
    return await bar(obj);
  } finally {
    obj.free();
  }
}

async function bar(obj: RObject) {
  const shelter: RObject[] = [];

  try {
    shelter.other = await webR.evalR('runif(1)');
    shelter.out = await webR.evalR('x + y', { x: obj, y: shelter.other});
    return await out.toNumber();
  } finally {
    webR.purge(shelter);
  }
}
```

Shelters may also be passed by arguments. This makes the memory management as granular as we want to. In this example, `foo()` creates a shelter that is also used by `bar()`:

```typescript
async function foo() {
  const shelter: RObject[] = [];

  try {
    shelter.obj = await webR.evalR('rnorm(1)');
    return await bar(obj, shelter);
  } finally {
    webR.purge(shelter);
  }
}

async function bar(obj: RObject, shelter: Shelter) {
  shelter.other = await webR.evalR('runif(1)');
  shelter.out = await webR.evalR('x + y', { x: obj, y: shelter.other});
  return await out.toNumber();
}
```

### Issues with the dictionary approach

Passing these shelters to other functions is potentially unsafe. For instance `bar()` does not necessarily know what objects have been added to `shelter` and might overwrite an object added upstack.

This could be worked around by structuring the shelter differently with a more verbose API (nested calls):

```typescript
async function bar(obj: RObject, shelter: Shelter) {
  const other = shelter.add(await webR.evalR('runif(1)'));
  const out = shelter.add(await webR.evalR('x + y', { x: obj, y: shelter.other}));
  return await out.toNumber();
}
```

### Shelters and `captureR()`

The minimalistic shelter API doesn't really work for `captureR()` which returns outputs in an array of `string | RObject`. The caller would have to loop over the output to add the `RObject` conditions to the shelter.

Alternatively, `captureR()` (and for consistency `evalR()` etc) could take a shelter as argument and be in charge of adding objects there.

```typescript
await evalR('1', undefined, shelter);
await captureR('1', undefined, undefined, shelter);
```

This requires users to memorise function signatures or look them up, and sort of hides the important task of memory management in auxiliary arguments.

## Evaluating shelters

In this proposal, shelters are objects that carry all the `webR` methods that are able to transfer R objects on the main thread. Instead of using `webR` to evaluate, you call the corresponding shelter method:

```typescript
async function foo() {
  // Create a new shelter
  const shelter = new webR.shelter();

  try {
    // Use it to evaluate and transfer objects there
    const obj = await shelter.evalR('rnorm(1)');

    // Pass it down by argument
    return await bar(obj, shelter);
  } finally {
    // Purge it all at once
    shelter.purge();
  }
}

async function bar(obj: RObject, shelter: Shelter) {
  // Evaluate within the shelter
  const other = await shelter.evalR('runif(1)');
  const out = await shelter.evalR('x + y', { x: obj, y: other});

  return await out.toNumber();
}
```

In addition, `webR` includes a "discarding shelter" (called `discard`?) that doesn't protect objects. It is useful when you need to evaluate R code only for side effects:

```typescript
async function printNorm(): void {
  await webR.discard.evalR('print(rnorm(1))');
}
```

The discarding shelter is easier to use than `free()` because the result is never protected. And easier to use than an extra argument because you don't need to look at the signature to see which argument you need to fill out, and don't need to closely inspect the call to determine which memory management steps are taken.

The `captureR()` issue is trivially solved by calling the corresponding shelter method:

```typescript
await shelter.captureR('1');

// Frees the result and all conditions
shelter.purge()
```

You can still evaluate with `webR.evalR()` and friends, in which case you must call `free()` manually. There is no `webR.purge()` method to free all objects at once because it would be easy to create incorrect code with it.

**Comment by georgestagg** [comment]
Thank you for this detailed write up!

Of the two proposals, I prefer the evaluating shelters over the more minimal object shelters, for the reasons you specify in the issues section - in particular the issues with freeing everything returned from `captureR()`. The API of your proposal with methods such as `shelter.evalR()` looks very reasonable to me.

I do agree that we should continue to support the original form of `webR.evalR()`. This is useful when experimenting in the JavaScript console, where memory management is not such of a worry. IIUC your proposal of leaving the responsibility to call `obj.free()` manually with the caller in the simplest case of using `webR.evalR()` is similar to how the Pyodide project deals with memory management, so I don't think it is unreasonable to provide this responsibility as an option. Some users with prior Pyodide experience may even prefer this.

Nice idea with the `discard` shelter, also. I like this a lot because a user does not have to worry about the `evalR()` argument signature when just executing for side effects.

Given the restrictions placed on us by the concurrency and lack of finalisers, I feel like the evaluating shelters with option of `webR.evalR()` scheme is a good compromise between strong memory safety and ease of use - A simple API for experimentation in a JS console, and a safe API for writing web applications with webR.

We should probably keep this issue open until we have not only merged a memory management scheme, but have also checked our own use of `evalR()` and `captureR()` internally and in the REPL demo to ensure they're memory safe by using the new scheme.

**Comment by lionel-** [comment]
We'll also need to invalidate freed `RObjects` such that a JS error is thrown if you try to do anything with them (this probably could be checked in `RProxy` right before initiating a channel message).

George noted that this means an object can only be protected by a single shelter, unless we add refcounting of some sort. We'll start with single shelters and see if this is sufficient for common needs.

**Comment by wch** [comment]
With the minimalistic shelter, is it possible for an object to be GC'd before it enters the shelter? For example, it's unclear to me how the following assignment to `shelter.obj` could reliably protect the R object, since the R stuff is happening on another thread. (Also, is it even possible for assignment to `shelter.obj` to cause the main thread to send a message to the R webworker thread?)

    ```js
    shelter.obj = await webR.evalR('rnorm(1)');
    ```

So if I'm understanding correctly, this form of shelter is a non-starter (though I would love to be proven wrong).

*****

With the evaluating shelters, I think people would find it confusing to have to deal with shelters when all they really want is a reference to an object. There are two reasons for this. First, the shelter is another object they'll have to pass around. Second, shelters in general are a concept that sort of sound like an R environments, but are in fact orthogonal to environments, and that's just one more thing that people will have to wrap their minds around.

Here's the example function from above:

```js
async function foo() {
  const shelter = new webR.shelter();
  try {
    const obj = await shelter.evalR('rnorm(1)');
    return await bar(obj, shelter);
  } finally {
    shelter.purge();
  }
}
```

* The shelter needs to exist (not be purged) as long as you want to keep a reference to the R object.
* But the shelter doesn't provide an interface to get at your object, so in addition to the `shelter` JS variable, you also need `obj`.
* So if you want keep `obj`, you also need to keep `shelter` (that is, if you want to be able to properly release the R memory held by `obj` and `shelter`).

The shelter makes sense in examples where you call a a JS function where which in turn does a bunch of R stuff, and then returns a JS object. But I think it would be inconvenient when you want to keep a handle to an R object.

For example, I might want to get a handle to an R function which I would later invoke from JS, or perhaps a handle to a data frame that I want to pass to an R function. In cases like this, having to manage the shelter in addition to the handle to the R object will just make things more complicated.

I think it makes sense for `webR.evalR()` to automatically protect objects, as George suggested, so that users don't have to manage shelters when working this way. (However, then this raises another question: are shelters useful enough to warrant having two ways to manage object lifetimes? Personally, I'm not fully convinced that the benefit of shelters a large one.)

*****

One more quick thought: if there are getting to be too many arguments to functions like `evalR()`, then I think it would be a good time to add an options object, as in:

```js
webR.evalR("1+1", { return: false });
```

**Comment by lionel-** [comment]
Thanks for you comments Wilson.

> With the minimalistic shelter, is it possible for an object to be GC'd before it enters the shelter? For example, it's unclear to me how the following assignment to shelter.obj could reliably protect the R object, since the R stuff is happening on another thread.

The minimalistic shelter doesn't do any protection. Because there is no reliable way to protect from the main thread, objects are always protected from the worker thread before being sent away.

The evaluating shelters don't necessarily perform the protection. In the first implementation, I'll probably just use the precious list. However, unlike minimalistic shelters, they potentially can be implemented with their own protection mechanism. We might have to consider this for performance: on the R side the singly-linked precious list may be slow when unprotecting out of order, and on the JS side many calls to the release method will cause as many channel communications.

> With the evaluating shelters, I think people would find it confusing to have to deal with shelters when all they really want is a reference to an object. There are two reasons for this.
> 
> First, the shelter is another object they'll have to pass around.

Yup there's no way around this. If you want very coarse granularity of unprotection (across function calls), you'll have to pass around some sort of containers to collect the objects. You can also create one shelter per function, or no shelters at all. The granularity is up to the user. The advantage of passing a shelter around is that the functions then don't have to worry about unprotecting in the correct way.

> Second, shelters in general are a concept that sort of sound like an R environments, but are in fact orthogonal to environments

I'm not sure I see what you mean. Do we at least agree that they don't sound like an environment you evaluate in? If you mean that they sound like an environment as a collection of objects, that seems fine because that can be conceived this way (at least the evaluating shelters, not the minimalistic ones). It doesn't matter from the point of view of the user if evaluating shelters are implemented with an environment, a hashtab (new data strucutre in recent versions of R), a list, or just the precious list.

> and that's just one more thing that people will have to wrap their minds around.

I was thinking that shelters are fairly straightforward:

- `webR.evalR()` uses a global shelter. You manage the objects individually.
- `myShelter.evalR()` uses a local one. You manage the objects collectively from the shelter.
- `webR.discard.evalR()` doesn't use any shelter.

In this approach, memory management is consistent in the sense that you first choose a location (`webR`, `myShelter`, or `webR.discard` to evaluate with. It is the least verbose solution, it doesn't require constant lookup of function signatures, and it still puts memory management on the forefront. This makes it easy to create correct code when writing and easy to evaluate the correctness of code when reading.

> I think it makes sense for webR.evalR() to automatically protect objects, as George suggested, so that users don't have to manage shelters when working this way.

Yes the default `evalR()` will protect on a global shelter that you can't purge, and so you'll have to make sure to call the release method for each object implicitly transferred to the main thread. This is the maximum granularity and also the method that makes it most likely to create leaks.

> are shelters useful enough to warrant having two ways to manage object lifetimes? Personally, I'm not fully convinced that the benefit of shelters a large one.

oh. I thought that the `captureR` example was doing a good job of showing the benefits of this approach. As well as the nested try/finally problem. Basically I think the granular unprotection will be fine in toy examples or in applications that perform very few R evaluations. But in more complex cases the shelters will have far better usablity.

**Comment by georgestagg** [comment]
IMO using an example with just a single object is not great at showing where shelters will be useful. In the case of a single object one could simply use the implicit global shelter with `obj = webR.evalR([...])` and then `obj.free()`. For more complex situations with multiple R object references and calls to `captureR` (where multiple `RObjects` could be returned at once), it becomes more clear why a coarse `shelter.purge()` is useful. For me, the convincing argument for shelters was exactly that possibility for `captureR` to return multiple objects that must be tracked or looped over to be freed.

I think when a user is working with webR, they are going to hit the following situations, in order:
 * I want to quickly and easily get a reference to an R object.
 * I just want to `evalR` for side effects and don't want to have to manage the results.
 * I am doing complex things and want help with managing memory.

Those three situations may be handled by,
 * `webR.evalR()`, with the user responsible for ensuring `obj.free()` is called,
 * `webR.discard.evalR()`,
 *  `myShelter.evalR()`.

But perhaps this ordering reveals a flaw. It will not be clear to a user who has not yet learned about shelters what is going on with `webR.discard.evalR()`. This might look very strange to them if they are not already aware of what a shelter is and that the `discard` property is one of them. So, perhaps we should consider that case again. I know it means changing argument signatures but for the discarding shelter we could have something like what Winston suggested,

```
webR.evalR('do_side_effect()', env, { discardObjects: true } )
```

This would override `evalR()` to use the discarding shelter, rather than the global shelter.

We already have a general `options` argument in place here for tweaks like `webR.evalR('x;y;z', env, { withAutoprint: true } )`, so I don't think this an unreasonable addition to the signature, and it can be well documented in the typedoc for the `options` argument interface. I suspect that while a little more verbose, this will make a lot more sense for users who have not yet learned about shelters.

P.S. Should `env` be part of the `options` interface already in place here? It would avoid things like, `webR.evalR('1;2;3', undefined, { withAutoprint: true })`. A question for another time perhaps.

---

A thought occurs about new R objects, currently we can do things like,

```
obj = await new webR.RDouble([1,2,3]);
```

which can be automatically protected on the worker thread and freed from the main thread.

However, should the shelter proposal also support new R objects? Probably they should. Since we have no way to add objects to a shelter in this initial scheme, we would need to duplicate the R constructor proxies that make this work so that they also exist as properties on the shelters.

```
obj = await new myShelter.RDouble([1,2,3]);
```

This is doable, but should to be kept in mind during implementation.

**Comment by georgestagg** [comment]
Thanks, I am not opposed to a separate function since we already have `evalR` and `captureR` with different behaviours. I like that TypeScript can enforce that this new function has return of `Promise<void>` and so we really are free to discard everything.

Of those names I'd vote for `doR`. There's also the option of `runR`. Let's see what Winston thinks.

**Comment by wch** [comment]
Thanks for the replies. I'm coming around to the use of shelters. I also agree with George's observation that `webR.discard` is a bit confusing because for it to make sense, the user first needs to understand shelters, and then they have to understand that `webR.discard` is the _absence_ of a shelter.

So the three cases would be something like this?

* `webR.evalR()`
* `webR.evalR0()`
* `shelter.evalR()`

I don't have a strong opinion about the names. `doR` sounds OK to me, as does `evalR0()`.

Even though the name `evalR0()` is a bit of verbose and clunky, it does signal to the user that there's something an important difference between it and plain `evalR()`. With `doR()`, the name doesn't make it obvious that it's significantly different from `evalR()`. But either one is fine with me.

Does a `captureR0()` also make sense? If so, that's a reason to use a name like `captureR0` (or some other suffix that is the same for `evalR` and `captureR`).
