### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jjesusfilho** [georgestagg/webR#6]
Hi, 

I got the following error message when tried to build: 

```
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /build.

```

**Comment by georgestagg** [comment]
Looks like `PWD` is probably going missing in the `Makefile`.

For now you might be get away with with running the commands manually,

```
mkdir -p build
docker build -t webr-build .
docker run --rm --mount type=bind,source=${PWD}/build,target=/app/webR webr-build
cp repl/index.html build/
```

**Comment by georgestagg** [comment]
Ah, that's the very last step of the build, but /app/webR/ now doesn't seem to exist at all inside the container. Maybe in this case we should just drop the mount and get the files out the container some other way.

For example, you could run,
```
docker run -it --rm webr-build /bin/bash
```
To enter the container and start bash, then run,
```
mkdir -p /app/webR
build_R.sh
```
When it's finished the output files will be inside the directory `/app/webR` inside the container. However, since we've skipped the bind mount you'll need to copy them out of the container somehow, for example by using `scp` or `rsync` to copy them onto the host machine or some server.
